apiVersion: v1
kind: ConfigMap
metadata:
  name: seller-config
  namespace: staging
data:
  NEXT_PUBLIC_SUPPORT_EMAIL: "support@vcgamers.com"
  NEXT_PUBLIC_SUPPORT_WHATSAPP: "081511111659"
  NEXT_PUBLIC_SUPPORT_EMAIL_LINK: "mailto:support@vcgamers.com"
  NEXT_PUBLIC_SUPPORT_WHATSAPP_LINK: "https://api.whatsapp.com/send/?phone=6281511111659&text&type=phone_number&app_absent=0"
  NEXT_PUBLIC_API_BASE_URL: "https://apis.vcgamers.io/seller"
  NEXT_PUBLIC_API_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjEzNzgyNDgsImlhdCI6MTY4OTc1NTg0OCwiaWQiOiI2YWZiZWM3MC1kNmQ1LTQ2ZWMtYWE5NS1jZTc0MGYwNzJhZWUifQ.ol3M0UrkN3xZ7npE1ZNkK-bZnrzm2uuJ96RGBa5aK04"
