apiVersion: v1
kind: ConfigMap
metadata:
  name: seller-config
  namespace: default
data:
  NEXT_PUBLIC_SUPPORT_EMAIL: "support@vcgamers.com"
  NEXT_PUBLIC_SUPPORT_WHATSAPP: "081511111659"
  NEXT_PUBLIC_SUPPORT_EMAIL_LINK: "mailto:support@vcgamers.com"
  NEXT_PUBLIC_SUPPORT_WHATSAPP_LINK: "https://api.whatsapp.com/send/?phone=6281511111659&text&type=phone_number&app_absent=0"
  NEXT_PUBLIC_API_BASE_URL: "https://apis.vcgamers.io/seller"
  NEXT_PUBLIC_API_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjI0MzMyMjEsImlhdCI6MTY5MDgxMDgyMSwiaWQiOiI2YWZiZWM3MC1kNmQ1LTQ2ZWMtYWE5NS1jZTc0MGYwNzJhZWUifQ.6HpnU3d1XabeG8duUF5VV24aryMCGSsc_u4hlv-TY5I"
  NEXT_PUBLIC_AUTH_URL: "https://auth-v2.vcgamers.io"
  NEXT_PUBLIC_API_URL: "https://apis.vcgamers.io/api"
  NEXT_PUBLIC_MARKET_URL: "https://market.vcgamers.io/"
  NEXT_PUBLIC_VCG_STORE_URL: "https://www.vcgamers.com/store/"
  NEXT_PUBLIC_WS_URL: "https://beta.vcg.asia"
  NEXT_PUBLIC_CREATE_NETCORE: "ADGMOT35CHFLVDHBJNIG50K9685GGC4IGEHKN2KCTUEA8BR1N320"
  NEXT_PUBLIC_REGISTER_NETCORE: "a0bd576f2ab743f5340e5f4143f6e30b"
  NEXT_PUBLIC_API_DOCS_URL: "https://documenter.getpostman.com/view/28289164/2s9YJjTKWG"
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyC_5C408Y8mce2yI7RjDVUcsWki3zm8Jro"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "vc-gamers.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "vc-gamers"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "vc-gamers.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "327843531831"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:327843531831:web:ecbabf499b1934de8c43b2"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "G-XBZLDKLH97"
  NEXT_PUBLIC_FIREBASE_VAPID_KEY: "BPMeVbGVjZuUXOZPGxikleNhiz7IPmNuGaT85uQAr8VYDM2GZQ2Z0RzpqKr9ijR7HGoPoJp5zQG7aPf9e4HrijI"
