apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seller
  namespace: staging
  annotations:
     traefik.ingress.kubernetes.io/router.middlewares: traefik-secureheaders@kubernetescrd
     name: seller
     namespace: staging
spec:
  rules:
    - host: "seller.vcgamers.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seller
                port:
                  number: 80
