apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seller
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-stg-vcg"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5M
    nginx.ingress.kubernetes.io/proxy-body-size: 5M
    #nginx.ingress.kubernetes.io/whitelist-source-range: "52.220.15.238,18.143.208.40,202.152.22.118,182.23.62.3,36.78.14.13,202.159.9.178"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "sameorigin";
      add_header X-Content-Type-Options nosniff;
      more_set_headers "X-Forwarded-For $http_x_forwarded_for";
      add_header Referrer-Policy 'same-origin';
      add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";
spec:
  tls:
  - hosts:
    - seller.vcg.my.id
    secretName: seller.vcg.my.id-tls
  ingressClassName: "nginx"
  rules:
  - host: seller.vcg.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seller
            port:
              number: 80
